/**
 * @fileoverview Example programs shown in the Code tab's Examples menu.
 *
 * Each one is checked by tests/unit/examples.test.js: it must run, and all
 * except "Mistakes on purpose" must produce no joint errors or warnings.
 * To add one: append an entry here.
 *
 * @module examples/jointExamples
 */

export const JOINT_EXAMPLES = [
    {
        id: 'box',
        title: 'Open box (finger joints)',
        description: 'Five panels and eight finger joints. Change h in Parameters and watch every tooth follow.',
        code: `param w 300
param d 200
param h 150
param t 6

shape rectangle base  { x: 0   y: 0   width: w height: d depth: t }
shape rectangle front { x: 0   y: 240 width: w height: h depth: t }
shape rectangle back  { x: 340 y: 240 width: w height: h depth: t }
shape rectangle west  { x: 340 y: 0   width: d height: h depth: t }
shape rectangle east  { x: 580 y: 0   width: d height: h depth: t }

join finger base.top    front.top
join finger base.right  east.top
join finger base.bottom back.top
join finger base.left   west.top
join finger front.left  east.right
join finger east.left   back.right
join finger back.left   west.right
join finger west.left   front.right
ground base
`
    },
    {
        id: 'shelf',
        title: 'Shelf (tab and slot, wedges)',
        description: 'Two sides, two boards; the lower board is locked with wedges.',
        code: `param t 6
param depth 280
param height 560
param inner 400

shape rectangle side_a { x: 0   y: 0 width: depth height: height depth: t }
shape rectangle side_b { x: 320 y: 0 width: depth height: height depth: t }
shape rectangle low    { x: 640 y: 0   width: inner height: depth depth: t }
shape rectangle high   { x: 640 y: 320 width: inner height: depth depth: t }

join tab_slot low.left   side_a.top.inset(140) { tabs: 2 lock: wedge }
join tab_slot low.right  side_b.top.inset(140) { tabs: 2 lock: wedge }
join tab_slot high.left  side_a.top.inset(420) { tabs: 2 }
join tab_slot high.right side_b.top.inset(420) { tabs: 2 }
ground side_a
`
    },
    {
        id: 'stool',
        title: 'Stool (cross lap + bolts)',
        description: 'Cross-lapped legs, seat bolted on with M5 bolts and captive nuts.',
        code: `param t 9

shape rectangle leg_a { x: 0   y: 0 width: 360 height: 380 depth: t }
shape rectangle leg_b { x: 400 y: 0 width: 360 height: 380 depth: t }
shape rectangle seat  { x: 0   y: 420 width: 360 height: 360 depth: t }

join cross_lap leg_a.top.at(180) leg_b.bottom.at(180)
join bolt leg_a.top seat.top.inset(180) { size: M5 count: 2 side: down }
ground seat
`
    },
    {
        id: 'splice_hinge',
        title: 'Splice and living hinge',
        description: 'A long panel spliced from two pieces, and a corner bent with a living hinge.',
        code: `shape rectangle top_a { x: 0   y: 0 width: 500 height: 300 depth: 6 }
shape rectangle top_b { x: 0   y: 340 width: 500 height: 300 depth: 6 }
join splice top_a.bottom top_b.top { style: knob count: 3 }

shape rectangle wrap_a { x: 560 y: 0 width: 200 height: 150 depth: 3 }
shape rectangle wrap_b { x: 800 y: 0 width: 200 height: 150 depth: 3 }
join hinge wrap_a.right wrap_b.left { fold: 90 radius: 20 }
`
    },
    {
        id: 'egg_crate',
        title: 'Egg-crate in a loop',
        description: 'Ribs cross-lapped into a spine, generated by a for loop.',
        code: `param ribs 4
param gap 130
shape rectangle spine { x: 0 y: 0 width: 560 height: 120 depth: 6 }
for i from 0 to ribs - 1 {
    shape rectangle rib { x: i * 160 y: 160 width: 120 height: 120 depth: 6 }
    join cross_lap spine.top.at(85 + i * gap) rib.bottom.at(60)
}
ground spine
`
    },
    {
        id: 'mistakes',
        title: 'Mistakes on purpose',
        description: 'A wall 6 mm too wide and a wrong edge name: see the warnings and the red parts in 3D.',
        code: `shape rectangle base  { width: 300 height: 200 depth: 6 }
shape rectangle front { x: 0   y: 240 width: 300 height: 150 depth: 6 }
shape rectangle back  { x: 340 y: 240 width: 306 height: 150 depth: 6 }
shape rectangle west  { x: 340 y: 0   width: 200 height: 150 depth: 6 }
shape rectangle east  { x: 580 y: 0   width: 200 height: 150 depth: 6 }
join finger base.top    front.top
join finger base.right  east.top
join finger base.bottom back.top
join finger base.left   west.top
join finger front.left  east.right
join finger east.left   back.right
join finger back.left   west.right
join finger west.left   front.right
join finger front.middle back.top
ground base
`
    }
];
